### ISSUE TITLE
Stunner chart needs to have nodeSelector: kubernetes.io/os: linux for pod specs

### ISSUE THREAD

**Issue by hach-que** [l7mp/stunner-helm#11]
If you deploy Stunner via Helm charts into a cluster with both Linux and Windows nodes, pods can get incorrectly scheduled on Windows nodes.

The Helm charts need to add the following to pod specs:

```yaml
nodeSelector:
  kubernetes.io/os: linux
```

**Comment by davidkornel** [comment]
Hi @hach-que 
I looked into your problem and realized we already included the `nodeSelector` in both stunner and stunner-gateway-operator Helm repos.
In the values.yaml: https://github.com/l7mp/stunner-helm/blob/main/helm/stunner/values.yaml#L76
In the templates: https://github.com/l7mp/stunner-helm/blob/main/helm/stunner/templates/stunner-deployment.yaml#L41 

When installing the chart you can create a `values.yaml` file locally and override the default `nodeSelector` value {}

values.yaml: 
```yaml
stunner:
  nodeSelector:
    kubernetes.io/os: linux
```

To use it:
`helm install stunner stunner/stunner -f values.yaml  --create-namespace --namespace=stunner`
