### ISSUE TITLE
gateway-operator container is crashlooping

### ISSUE THREAD

**Issue by oleksandrfatikov** [l7mp/stunner-helm#18]
Hi,

I started experiencing issue with gateway operator after updating k8s cluster to v1.27.2.
Container crashlooping with the following error at startup:
`2023-09-19T17:27:04.471283419Z  INFO    setup   endpoint discovery      {"state": true}
2023-09-19T17:27:04.471510146Z  INFO    setup   setting up Kubernetes controller manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1281af0]
023-09-19T17:27:04.471283419Z  INFO    setup   endpoint discovery      {"state": true}
2023-09-19T17:27:04.471510146Z  INFO    setup   setting up Kubernetes controller manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1281af0]
goroutine 1 [running]:`

In v1.26 there was no such issue.
Another thing is that I had the same error  with helm, updating helm to v3.12.3 fixed it.
According to https://github.com/kubernetes/kubernetes/issues/119316#issuecomment-1636230050 the reason may be outdated client-go version.

Let me know if you any additional info.
Thanks!

**Comment by levaitamas** [comment]
hi @oleksandrfatikov,

Oh, this is new for us. We run test with k8s v1.27 in minikube with no such issues.
We are eager to help you. Could you please give us some additional context such as
- your cloud provider / kubernetes distro,
- stunner version,
- a full kubectl describe and kubectl log output of the stunner-gateway-operator pod? (please hide sensitive info)

Can you also please check if the problem occurs when installing the stunner development version? (Install notes here: https://github.com/l7mp/stunner-helm#development-version)

Thanks!

**Comment by oleksandrfatikov** [comment]
Hi @levaitamas ,

> Can you also please check if the problem occurs when installing the stunner development version? (Install notes here: https://github.com/l7mp/stunner-helm#development-version)

Using dev version seems to have helped!
The container is up and running, I'll monitor it for some time, but looks good so far.
Thanks!

As for requested info:
> your cloud provider / kubernetes distro,
Provider is Oracle Cloud.
> stunner version,
0.15.0
> a full kubectl describe and kubectl log output of the stunner-gateway-operator pod? (please hide sensitive info)
Attached.
[stunner-gateway-operator.log](https://github.com/l7mp/stunner-helm/files/12666196/stunner-gateway-operator.log)
[stunner-gateway-operator-describe.txt](https://github.com/l7mp/stunner-helm/files/12666197/stunner-gateway-operator-describe.txt)

**Comment by levaitamas** [comment]
I am happy to hear that the dev version solves this issue. In the next 1-2 weeks, we plan to release a new stable version. 

BTW nice catch,  we use k8s.io/client-go v0.26.0 in the v0.15.0 release indeed: https://github.com/l7mp/stunner-gateway-operator/blob/eb13f8d347d9323431312678d5aebfc399ab14cb/go.mod#L15
The dev version uses k8s.io/client-go v0.28.1, which works on k8s v1.27 in our tests and in your setup as well.

Thanks again for reporting this issue and checking the dev version!
