### ISSUE TITLE
Ship new helm chart release

### ISSUE THREAD

**Issue by iterion** [l7mp/stunner-helm#19]
Recent updates to stunner-auth-service meant that our auth service was updated over the weekend and broke URL generation for clients. This happened because the `dev` tag gets updated every push, which totally makes sense for dev.

https://github.com/l7mp/stunner-helm/commit/1a5274ec7648ab838376f3eb5b15a54de092abad would help us a lot to prevent this. For now, we've hard-coded everything at 0.15.0 but we'd like to go back to using the helm chart.

 I dunno if it's possible to get just a 0.15.1 to cover this bugfix. Or, if just shipping the latest main helm chart would work. We appreciate the work you've done and look forward to 0.16.0. 😄

**Comment by deagle99** [comment]
The same here. Also, it's necessary to mention that a few days ago new Helm values for Stunner auth were added, and an image with a `0.15.0` tag was expected to work by default but inside the Deployment resource of the `stunner-auth-service.yaml`  file,  but it actually doesn't work cuz the image related details cannot be consumed from Values file.

**Comment by levaitamas** [comment]
Hi!

The new [v0.16.0](https://github.com/l7mp/stunner/releases/tag/v0.16.0) release is out!  I hope it will serve you well. If you encounter any issues, please let us know. Closing this issue for now.
