### ISSUE TITLE
API version problem in dataplane manifest

### ISSUE THREAD

**Issue by adghanbari** [l7mp/stunner-helm#22]
Hello, 
I after using the latest verion 0.17.0 using argocd I noticed an error regarding the api version for dataplane manifest. I checked the file here : helm/stunner-gateway-operator/templates/stunner-default-dataplane.yaml and noticed that the api version is still in alpha. could you please change it to v1 ?

{{- if eq .Values.stunnerGatewayOperator.dataplane.mode "managed"}}
{{- with .Values.stunnerGatewayOperator.dataplane.spec }}
**apiVersion: stunner.l7mp.io/v1alpha1**
kind: Dataplane
metadata:
  name: default
spec:
  replicas: {{ .replicas }}
  image: {{ .image }}
  imagePullPolicy: {{ .imagePullPolicy }}
  command:
    {{- range .command }}
    - {{ . }}
    {{- end }}
  args:
    {{- range .args }}
    - {{ . }}
    {{- end }}
  {{- with .env }}
  env: {{- toYaml . | nindent 2 }}
  {{- end }}
  resources: {{- toYaml .resources | nindent 4 }}
  terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
  enableMetricsEndpoint: {{ .enableMetricsEndpoint }}
  hostNetwork: {{ .hostNetwork }}
  {{- with .affinity }}
  affinity: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .securityContext }}
  securityContext: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .tolerations }}
  tolerations: {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
{{- end -}}

**Comment by levaitamas** [comment]
Hi @adghanbari! Thanks for reporting this issue! I pushed a fix recently and re-released the v0.17.0 stunner-gateway-operator helm chart.
