### ISSUE TITLE
Stunnerd tag should be pinned to a specific version

### ISSUE THREAD

**Issue by dbason** [l7mp/stunner-helm#23]
Seeing as the CDS websocket communication is changing across versions the stunnerd image tag should be pinned to the version of the controller e.g. you could use `{{ Chart.AppVersion }}`

**Comment by levaitamas** [comment]
hi @dbason !

Is this still an issue? If so, can you please give some context?

**Comment by dbason** [comment]
I'm not sure if it's an issue with future versions as we are currently on 0.16 due to the version of the gateway API.  That said I think in general pinning the version of the image deployed to the AppVersion in the chart is best practice.

The main context is that the dataplane and the controller communicate over a websocket.  If the contract of that communication changes (which I noticed it did going from v0.16 -> v0.18) then as part of the helm chart those versions should be forcibly aligned.

**Comment by levaitamas** [comment]
I see your poblem, thanks for the explanation! Good news is we fixed the version number and the latest release (v0.18) uses the image tag `0.18` instead of `latest`. Closing this issue for now, but feel free to reopen if you encounter any further issues on this matter. Thanks for your report!
