### ISSUE TITLE
podDisruptionBudgets

### ISSUE THREAD

**Issue by davhdavh** [l7mp/stunner-helm#27]
Please add a default pdb that sets maxUnavailable to 1

**Comment by levaitamas** [comment]
hi @davhdavh! Could you please give us some context? Thanks!

**Comment by davhdavh** [comment]
podDisruptionBudgets prevents the system from voluntarily evicting the pod.
So e.g. if a node is going down for maintainance, with a pdb in place, it would wait until the pod is safely running on another node before shutting down the node.
