### ISSUE TITLE
Add imagePullSecrets to the stunner-gateway-operator deployments

### ISSUE THREAD

**Issue by seumasdunlop** [l7mp/stunner-helm#30]
To pull from a registry that requires authentication in kubernets you need to add `imagePullSecrets` to either the pod or the service account that the pod is running in.  I suggest adding it to each of the deployments.  It's already supported in the `Dataplane` resource.

I'm happy to put a pull request in for this if it is acceptable.

**Comment by levaitamas** [comment]
hi @seumasdunlop, 

Sounds reasonable to me. PRs are welcome!

**Comment by rg0now** [comment]
The verdict is that there's no need to customize this in the default Dataplane. Instead, just create your own custom Dataplane and let STUNner use that as a template for creating `stunnerd` pods (this can be set in the GatewayConfig).

Closing this for now, but feel free to reopen of something comes up.

**Comment by seumasdunlop** [comment]
@rg0now I can see that it's supported in the `Dataplane` custom resource so `imagePullSecrets` can be set on any pods created by that  but it isn't in the deployments created directly by the chart.  E.g. `stunner-auth` and `stunner-gateway-operator-controller-manager`.

**Comment by rg0now** [comment]
OK, now I get it, thanks @seumasdunlop  for the clarification. Reopening this issue now. 

Hope someone submits a PR until next week. Otherwise fixing this may remain to be done after v1.

**Comment by seumasdunlop** [comment]
Apologies, I didn't see your reply until today.  I've created a pull request for this - hopefully it can make v1.
https://github.com/l7mp/stunner-helm/pull/32
