### ISSUE TITLE
Make stunner-auth replicas configurable

### ISSUE THREAD

**Issue by iterion** [l7mp/stunner-helm#39]
As far as I know, it should be safe to run more than one replica of stunner-auth, but unfortunately we can't currently configure that with the helm chart.

Currently, it's hard coded to 1:
https://github.com/l7mp/stunner-helm/blob/9b1c55349d60f654ea36fb042bac6212f189a693/helm/stunner-gateway-operator/templates/stunner-auth-service.yaml#L15

Happy to make a PR if there is nothing I'm missing w.r.t. running more than one replica.

**Comment by rg0now** [comment]
Thx, this seems useful. Pls submit a PR, happy to merge.
