### ISSUE TITLE
securityContext issues on containers

### ISSUE THREAD

**Issue by cjvirtucio87** [l7mp/stunner-helm#43]
My cluster enables the [Pod Security admission controller](https://kubernetes.io/docs/concepts/security/pod-security-admission/), which requires every pod to adhere to [pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/):

```
W1201 09:34:55.535139   14754 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "stunner-auth-server" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "stunner-auth-server" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "stunner-auth-server" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "stunner-auth-server" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

Some of the resources need to have the `securityContext` of their containers be configurable to resolve this. I've added a [PR](https://github.com/l7mp/stunner-helm/pull/42) that should address this.

**Comment by davidkornel** [comment]
Hello there again,

We are confused about the logs you included in your comment:
`...allowPrivilegeEscalation != false (container "stunner-auth-server" must set securityContext.allowPrivilegeEscalation=false)...`

If you used the default hardcoded value for the auth-service, why does it say it is not set to false?
```
   securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
```

**Comment by cjvirtucio87** [comment]
> Hello there again,
> 
> We are confused about the logs you included in your comment: `...allowPrivilegeEscalation != false (container "stunner-auth-server" must set securityContext.allowPrivilegeEscalation=false)...`
> 
> If you used the default hardcoded value for the auth-service, why does it say it is not set to false?
> 
> ```
>    securityContext:
>       allowPrivilegeEscalation: false
>       capabilities:
>         drop:
>         - ALL
> ```

that's likely from when I was messing around with my fork. here's the `FailedCreate` event when using the version of the helm chart [before exposing the auth server's container securityContext](https://github.com/l7mp/stunner-helm/commit/9b1c55349d60f654ea36fb042bac6212f189a693#diff-e81e13daadd1745de51d8b8d85fce1fcd9be355732b64d60a6b56e18c28388caR56):

```
28s         Warning   FailedCreate        replicaset/stunner-auth-7d89c77c44   (combined from similar events): Error creating: pods "stunner-auth-7d89c77c44-5q4dk" is forbidden: violates PodSecurity "restricted:latest": runAsNonRoot != true (pod or container "stunner-auth-server" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "stunner-auth-server" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by cjvirtucio87** [comment]
all good now, latest version of the chart works:

```console
% helm install \
      stunner \
      "${STUNNER_CHART_NAME}" \
        --namespace stunner \
        --create-namespace \
        --values "${values_path}"

...

% kubectl --namespace stunner get pods/stunner-auth-5778ccd49c-78gc2 --output yaml

...

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
```

thank you for the assistance

**Comment by cjvirtucio87** [comment]
hi again, @davidkornel , I have [another PR](https://github.com/l7mp/stunner-helm/pull/45). I missed the operator as I was focused on the auth-service and the default dataplane. I can re-open this issue, re-open a new one, but I think my new PR should pretty much cover all that's left.
